apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-tekton-2
spec:
  description: |
    this pipeline offers a typical CI/CD process, with a flow including:
    - fetching a git repository as the source
    - using buildah to build a Docker image by Dockerfile
  params:
  - name: repo-url
    type: string
    description: The git repository URL to clone from.
  - name: tag-name
    type: string
    description: The git tag to clone.    
  - name: maven-image
    type: string
    description: Image for compile pom
    default: 'gcr.io/cloud-builders/mvn@sha256:8f38a2667125a8d83f6e1997847fedb6a06f041c90e2244884153d85d95f869b'
  workspaces:
    - name: workspace
    - name: maven-settings
    - name: empty-dir      
  tasks:
    - name: git-clone-2
      taskRef:
        kind: Task
        name: git-clone-2
      params:
        - name: url
          value: $(params.repo-url)
      workspaces:
      - name: output
        workspace: workspace        
    - name: list-directory
      taskRef:
        kind: Task
        name: list-directory
      runAfter:
        - git-clone-2
      workspaces:
      - name: directory
        workspace: workspace            
    - name: maven
      runAfter:
      - list-directory
      params:
      - name: GOALS
        value:
          - -B
          - -DskipTests
          - clean
          - package
      - name: MAVEN_IMAGE
        value: $(params.maven-image)      
      taskRef:
        kind: Task
        name: maven    
      workspaces:
      - name: maven-settings
        workspace: maven-settings
      - name: source
        workspace: workspace
