/*
 * Inserta informacion de  seguimientos
 */
db.seguimientos.insertMany([
    {
      "_id":"55af0ea155827301001a0cc8",
      "COMENTARIOS":"Se agenda evento para realizar dictamen en la proxima sesion",
      "PERITO":"Mtro. Pedro Diaz ",
      "GOBIERNO":"APF",
      "SIGLAS":"IMSS",
      "DEPENDENCIA":"Instituto Mexicano del Seguro Social",
      "CLAVEUC":"019GYR055",
      "NOMBRE_DE_LA_UC":"IMSS-Hospital de Especialidades Dr. Antonio Fraga Mouret",
      "RESPONSABLE":"Ernesto Alonso Ayala López",
      "NUMERO_EXPEDIENTE":"718952",
      "TITULO_EXPEDIENTE":"SERVICIO INTEGRAL DE HEMODINAMIA, ANGIOLOGIA Y NEUROLOGIA",
      "PLANTILLA_EXPEDIENTE":"01. Licitación Pública Nacional LAASSP",
      "NUMERO_PROCEDIMIENTO":"LA-019GYR055-N28-2014",
      "EXP_F_FALLO":"2014-12-12 00:00:00 GMT",
      "PROC_F_PUBLICACION":"2014-11-27 12:51",
      "FECHA_APERTURA_PROPOSICIONES":"2014-12-10 13:00",
      "CARACTER":"Nacional",
      "TIPO_CONTRATACION":"Servicios",
      "TIPO_PROCEDIMIENTO":"Licitación Pública",
      "FORMA_PROCEDIMIENTO":"Mixta",
      "CODIGO_CONTRATO":"694195",
      "TITULO_CONTRATO":"SERVICIO INTEGRAL DE TERAPIA ENDOVASCULAR",
      "FECHA_INICIO":"2015-01-01",
      "FECHA_FIN":"2015-12-31",
      "IMPORTE_CONTRATO":"7400100",
      "MONEDA":"MXN",
      "ESTATUS_CONTRATO":"Activo",
      "ARCHIVADO":"No",
      "RAMO":"",
      "CLAVE_PROGRAMA":"",
      "APORTACION_FEDERAL":"",
      "FECHA_CELEBRACION":"2014-12-22 00:00:00 GMT",
      "CONTRATO_MARCO":"0",
      "COMPRA_CONSOLIDADA":"0",
      "PLURIANUAL":"0",
      "CLAVE_CARTERA_SHCP":"",
      "ESTRATIFICACION_MUC":"No MIPYME",
      "PROVEEDOR_CONTRATISTA":"LEVBETH MEDICAL SA DE CV",
      "ESTRATIFICACION_MPC":"Mediana",
      "ESTATUS_EMPRESA":"Habilitado",
      "CUENTA_ADMINISTRADA_POR":"PoC",
      "ANUNCIO":"https://compranet.funcionpublica.gob.mx/esop/guest/go/opportunity/detail?opportunityId=488586"
   },
   {
      "_id":"55af0ea155827301001a0cc9",
      "COMENTARIOS":"Se aprobo el dictamen pero se rechazo en el UCI de la seccion 22 por falta de chuleta de documentos",
      "PERITO":"Mtro. Pedro Diaz ",
      "GOBIERNO":"APF",
      "SIGLAS":"IMSS",
      "DEPENDENCIA":"Instituto Mexicano del Seguro Social",
      "CLAVEUC":"019GYR055",
      "NOMBRE_DE_LA_UC":"IMSS-Hospital de Especialidades Dr. Antonio Fraga Mouret",
      "RESPONSABLE":"Ernesto Alonso Ayala López",
      "NUMERO_EXPEDIENTE":"718952",
      "TITULO_EXPEDIENTE":"SERVICIO INTEGRAL DE HEMODINAMIA, ANGIOLOGIA Y NEUROLOGIA",
      "PLANTILLA_EXPEDIENTE":"01. Licitación Pública Nacional LAASSP",
      "NUMERO_PROCEDIMIENTO":"LA-019GYR055-N28-2014",
      "EXP_F_FALLO":"2014-12-12 00:00:00 GMT",
      "PROC_F_PUBLICACION":"2014-11-27 12:51",
      "FECHA_APERTURA_PROPOSICIONES":"2014-12-10 13:00",
      "CARACTER":"Nacional",
      "TIPO_CONTRATACION":"Servicios",
      "TIPO_PROCEDIMIENTO":"Licitación Pública",
      "FORMA_PROCEDIMIENTO":"Mixta",
      "CODIGO_CONTRATO":"694032",
      "TITULO_CONTRATO":"SERVICIO DE TERAPIA ENDOVASCULAR NEUROCIRUGIA",
      "FECHA_INICIO":"2015-01-01",
      "FECHA_FIN":"2015-12-31",
      "IMPORTE_CONTRATO":"9086495",
      "MONEDA":"MXN",
      "ESTATUS_CONTRATO":"Activo",
      "ARCHIVADO":"No",
      "RAMO":"",
      "CLAVE_PROGRAMA":"",
      "APORTACION_FEDERAL":"",
      "FECHA_CELEBRACION":"2014-12-22 00:00:00 GMT",
      "CONTRATO_MARCO":"0",
      "COMPRA_CONSOLIDADA":"0",
      "PLURIANUAL":"0",
      "CLAVE_CARTERA_SHCP":"",
      "ESTRATIFICACION_MUC":"No MIPYME",
      "PROVEEDOR_CONTRATISTA":"LEVBETH MEDICAL SA DE CV",
      "ESTRATIFICACION_MPC":"Mediana",
      "ESTATUS_EMPRESA":"Habilitado",
      "CUENTA_ADMINISTRADA_POR":"PoC",
      "ANUNCIO":"https://compranet.funcionpublica.gob.mx/esop/guest/go/opportunity/detail?opportunityId=488586"
   },
   {
      "_id":"55af0ea155827301001a0cca",
      "COMENTARIOS":"Se agenda evento para realizar dictamen en la proxima sesion",
      "PERITO":"Mtro. Pedro Diaz ",
      "GOBIERNO":"APF",
      "SIGLAS":"IMSS",
      "DEPENDENCIA":"Instituto Mexicano del Seguro Social",
      "CLAVEUC":"019GYR067",
      "NOMBRE_DE_LA_UC":"IMSS-UMAE HOSPITAL DE PEDIATRÍA SILVESTRE FRENK FREUND DEL CMN SIGLO XXI",
      "RESPONSABLE":"Francisco Gómez Jiménez",
      "NUMERO_EXPEDIENTE":"709739",
      "TITULO_EXPEDIENTE":"SERVICIO DE MANTENIMIENTO A ÁREAS VERDES, PÉTREAS Y MACETONES DE ÁREAS COMUNES ",
      "PLANTILLA_EXPEDIENTE":"01. Licitación Pública Nacional LAASSP",
      "NUMERO_PROCEDIMIENTO":"LA-019GYR067-N183-2014",
      "EXP_F_FALLO":"2014-12-10 00:00:00 GMT",
      "PROC_F_PUBLICACION":"2014-11-17 18:12",
      "FECHA_APERTURA_PROPOSICIONES":"2014-12-03 10:00",
      "CARACTER":"Nacional",
      "TIPO_CONTRATACION":"Servicios",
      "TIPO_PROCEDIMIENTO":"Licitación Pública",
      "FORMA_PROCEDIMIENTO":"Electrónica",
      "CODIGO_CONTRATO":"685884",
      "TITULO_CONTRATO":"CONTRATO DE SERVICIOS DE MANTENIMIENTO DE ÁREAS VERDES , PÉTREAS Y MACETONES",
      "FECHA_INICIO":"2015-01-01",
      "FECHA_FIN":"2015-12-31",
      "IMPORTE_CONTRATO":"1273247.73",
      "MONEDA":"MXN",
      "ESTATUS_CONTRATO":"Activo",
      "ARCHIVADO":"No",
      "RAMO":"",
      "CLAVE_PROGRAMA":"",
      "APORTACION_FEDERAL":"",
      "FECHA_CELEBRACION":"",
      "CONTRATO_MARCO":"0",
      "COMPRA_CONSOLIDADA":"0",
      "PLURIANUAL":"0",
      "CLAVE_CARTERA_SHCP":"",
      "ESTRATIFICACION_MUC":"Pequeña",
      "PROVEEDOR_CONTRATISTA":"EDIL GC SA DE CV",
      "ESTRATIFICACION_MPC":"Pequeña",
      "ESTATUS_EMPRESA":"Habilitado",
      "CUENTA_ADMINISTRADA_POR":"PoC",
      "ANUNCIO":"https://compranet.funcionpublica.gob.mx/esop/guest/go/opportunity/detail?opportunityId=483917"
   },
   {
      "_id":"55af0ea155827301001a0ccb",
      "COMENTARIOS":"No se Aprueba por falta de quorum en la junta del evento de acta constitutiva",
      "PERITO":"Mtro. Pedro Diaz ",
      "GOBIERNO":"APF",
      "SIGLAS":"IMSS",
      "DEPENDENCIA":"Instituto Mexicano del Seguro Social",
      "CLAVEUC":"019GYR060",
      "NOMBRE_DE_LA_UC":"IMSS-Hospital de Pediatria del CMN de occidente",
      "RESPONSABLE":"José de Jesús Arriaga Davila",
      "NUMERO_EXPEDIENTE":"735101",
      "TITULO_EXPEDIENTE":"Dialisis Peritoneal Automatizada para Pacientes Prevalentes 2015",
      "PLANTILLA_EXPEDIENTE":"04. Invitación a cuando menos tres Nacional LAASSP",
      "NUMERO_PROCEDIMIENTO":"IA-019GYR060-N33-2014",
      "EXP_F_FALLO":"2014-12-29 00:00:00 GMT",
      "PROC_F_PUBLICACION":"2014-12-18 14:40",
      "FECHA_APERTURA_PROPOSICIONES":"2014-12-24 09:15",
      "CARACTER":"Nacional",
      "TIPO_CONTRATACION":"Adquisiciones",
      "TIPO_PROCEDIMIENTO":"Invitación a Cuando Menos 3 Personas",
      "FORMA_PROCEDIMIENTO":"Mixta",
      "CODIGO_CONTRATO":"694452",
      "TITULO_CONTRATO":"Dialisis Peritoneal Automatizada para Pacientes Prevalentes 2015",
      "FECHA_INICIO":"2015-01-01",
      "FECHA_FIN":"2015-12-31",
      "IMPORTE_CONTRATO":"1807272",
      "MONEDA":"MXN",
      "ESTATUS_CONTRATO":"Activo",
      "ARCHIVADO":"No",
      "RAMO":"",
      "CLAVE_PROGRAMA":"",
      "APORTACION_FEDERAL":"",
      "FECHA_CELEBRACION":"2015-01-09 00:00:00 GMT",
      "CONTRATO_MARCO":"0",
      "COMPRA_CONSOLIDADA":"0",
      "PLURIANUAL":"0",
      "CLAVE_CARTERA_SHCP":"",
      "ESTRATIFICACION_MUC":"No MIPYME",
      "PROVEEDOR_CONTRATISTA":"LABORATORIOS PISA S.A. DE C.V.",
      "ESTRATIFICACION_MPC":"No MIPYME",
      "ESTATUS_EMPRESA":"Habilitado",
      "CUENTA_ADMINISTRADA_POR":"PoC",
      "ANUNCIO":"https://compranet.funcionpublica.gob.mx/esop/guest/go/opportunity/detail?opportunityId=495765"
   }
])
