apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: git-clone-2
spec:
  taskRef:
    kind: Task
    name: git-clone-2
  params:
  - name: url
    value: https://github.com/delizaSG/MicroService-UCI-Seguimiento.git
  - name: deleteExisting
    value: "true"
  workspaces:
    - name: output
      #emptyDir: {}
      persistentVolumeClaim:
        claimName: pvc-c9acb3d094
