apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: list-directory-
spec:
  taskRef:
    name: list-directory
  workspaces:
    - name: directory
      persistentVolumeClaim:
        claimName: pvc-c9acb3d094
