apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: buildah-run-
spec:
  taskRef:
    name: buildah
  params:
    - name: IMAGE
      value: 'image-registry.openshift-image-registry.svc:5000/user5/uci-service:v2'
      #value: 'docker.io/dodiliz/uci-service:v2'
    - name: TLSVERIFY
      value: 'false'
    - name: STORAGE_DRIVER
      value: 'vfs'
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: pvc-c9acb3d094
  serviceAccountName: tekton-pipeline
